apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react-app-ns
  labels:
     app: react-app
     tier: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"

